const inicio = document.getElementById('botao');

inicio.addEventListener("click", function() {
    
    let nome = prompt('Escreva seu nome ');
    let sobrenome = prompt('Escreva seu sobrenome');
    let completo = `${nome} ${sobrenome}` ;


    alert(`{Yusano}: Olá meu nome Yusano estou chegando agora no JavaScript  Há, mas acho que me lembro de você 
    você não é ${completo} a quanto tempo skksksks 😊


    `)


    
  });